### ISSUE TITLE
Running stored procedure fails with "listener must be a function"

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-cosmosdb-node#119]
I am trying to run a stored procedure with the following code:

```
client.executeStoredProcedure(sprocLink, options, callback);
```

However, the app crashes with the error "listener must be a function". I am using SDK 1.5.6.

Here is the relevant stack track:

```
DOMAIN ERROR CAUGHT TypeError: listener must be a function
    at ClientRequest.once (events.js:251:11)
    at createRequestObject (/home/murdockcrc/repos/hdv/node_modules/documentdb/lib/request.js:102:18)
    at Object.RequestHandler.request (/home/murdockcrc/repos/hdv/node_modules/documentdb/lib/request.js:154:32)
    at DocumentClient.Base.defineClass.post (/home/murdockcrc/repos/hdv/node_modules/documentdb/lib/documentclient.js:2031:35)
    at DocumentClient.Base.defineClass.executeStoredProcedure (/home/murdockcrc/repos/hdv/node_modules/documentdb/lib/documentclient.js:1821:18)
    at AzureDbHelper.executeStoredProcedure 
```

**Comment by murdockcrc** [comment]
I have downgraded to version 1.2.2 and the error does not occur. It starts occuring again in version 1.4.0.

**Comment by mimig1** [comment]
@aliuy - You were going to investigate. Can you provide an update for @murdockcrc?

**Comment by murdockcrc** [comment]
@mimig1 , @aliuy : just wanted to check if you guys need some more info or assistance in reproducing? Thanks.

**Comment by koltachev** [comment]
This looks like the callback you pass (client.executeStoredProcedure(sprocLink, options, callback)) is not a function. The issue here most likely is that you don't provide the "params" argument, here the definition of [executeStoredProcedure](https://github.com/Azure/azure-documentdb-node/edit/master/source/lib/documentclient.js):
        executeStoredProcedure: function (sprocLink, params, options, callback) 

DocDB SDK shifts if options are not provided, but it doesn't shift if there are no params.

So, this should fix the issue, try calling like this:
client.executeStoredProcedure(sprocLink, [], options, callback);

Can you please try and let us know?

Thanks,
Michael

**Comment by murdockcrc** [comment]
Close, in fact, the following change pulled the trick:
client.executeStoredProcedure(sprocLink, options, null, callback);

I suppose the signature of this function was changed in between releases of the SDK?

Thanks

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
