### ISSUE TITLE
client.createDatabase swallowing errors

### ISSUE THREAD

**Issue by sebastus** [Azure/azure-cosmosdb-node#122]
If you provide an invalid endpoint such as:

http:https://whatever.documents.azure.com:443/

createDatabase throws, but never returns.

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
