### ISSUE TITLE
readMedia is dropping bytes when reading a binary file (e.g. jpeg)

### ISSUE THREAD

**Issue by limeybastow** [Azure/azure-cosmosdb-node#168]
I successfully uploaded a jpeg file as an attachment but when trying to retrieve it via the readMedia call it was coming back smaller than it went in.

I was able to successfully download the attachment media via Postman so I knew it was correctly uploaded.

In digging through the code I think I found the issue in the createRequestObject (line 49 in request.js).  When handling the response data event it appears that bytes are being dropped when appending the chunk to the data string.  My guess is that there are some bytes that make a string unhappy and either the string is being truncated or the characters are being dropped.

To test the theory I modified the code response.on('data' to read as follows:

        var data = "";
        var length = 0;
        var lastChunk = null;
        response.on("data", function(chunk) {
            data += chunk;
            length += chunk.length;
            lastChunk = chunk;
        });

data.length - length was always growing throughout the processing of the response.

**Comment by limeybastow** [comment]
I changed the MediaReadMode in the connection policy to Streamed and handled the response directly.  This resolved my issue and may be the best way to handle binary files, however this should be noted in the documentation.

**Comment by moderakh** [comment]
@limeybastow thank you for reporting this. I think this should work in any `MediaReadMode` meaning that's a bug.

I suspect the root cause is what you guessed and there are some bytes that make a string unhappy.

Are you interested in provide a fix patch for this? I will merge your patch as your contribution if you do so.

**Comment by limeybastow** [comment]
I've been pondering how it might be fixed without making a breaking change for anyone who's currently successfully using it to return text documents.  One thought I had was to look at the content type and if it was not some sort of text file (text, html, xml etc.) to return a node Buffer object instead of a string.

**Comment by moderakh** [comment]
@ato9000 @rnagpal any suggestion on this?

**Comment by rnagpal** [comment]
I was looking at the .NET version of our SDK and it seems the Media(that represents the attachment content) is of Stream type, so looks like we always return a stream which can be converted based on the content-type. So I'm fine returning a node Buffer object(if that's the equivalent of Stream in Node) for all cases and let the user handle it.

**Comment by limeybastow** [comment]
@rnagpal - A node Buffer isn't a stream.  It's just a byte array.  In the node version of the SDK you can set the MediaReadMode to either Streamed or Buffered when you connect.  If you set it to Streamed it returns a stream that works fine with binary files.  If you set it to Buffered it's currently returning a string.  I ended up just change the mode to Streamed and that worked fine for me so I wouldn't have a problem with having the Buffered dropped completely and thus obsolete the MediaReadMode option.

If we wanted to keep the Buffered mode it should probably be converted to a node Buffer instead of a string or have an option to choose one or the other but in either case it would create a breaking change.

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
