### ISSUE TITLE
Export AzureDocuments.ConnectionPolicy

### ISSUE THREAD

**Issue by briancr-ms** [Azure/azure-cosmosdb-node#187]
In order to enable clients to use the default ConnectionPolicy and override parts of it (like RetryOptions), AzureDocuments.ConnectionPolicy should be exported, so clients can write code like:

(In Typescript)
// Get the default ConnectionPolicy.
let connectionPolicy = new AzureDocuments.ConnectionPolicy();
// Override RetryOptions.
connectionPolicy.RetryOptions = { MaxRetryAttemptCount: 20, MaxWaitTimeInSeconds: 60 }

**Comment by PrashanthCorp** [comment]
Is there a workaround to this?

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
