### ISSUE TITLE
Change feed support?

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-cosmosdb-node#208]
According to the [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed#rest-apis), "You can also retrieve the feed of documents using one of the supported Azure Cosmos DB SDKs". I presume this module is not one of the supported "SDKs" as I'm not seeing a like-named API. Any plans for supporting this?

**Comment by ssured** [comment]
It would be really nice to have node support for the changes feed functionality. Any updates / roadmap? Thanks

**Comment by adihe** [comment]
Yes this feature is crucial.

**Comment by southpolesteve** [comment]
@adihe ChangeFeed is supported in our v3 SDK https://github.com/Azure/azure-cosmos-js/blob/master/samples/ChangeFeed.ts

**Comment by adihe** [comment]
Thank you very much.
