### ISSUE TITLE
Aggregate query on single partition collection may return multiple values

### ISSUE THREAD

**Issue by khdang** [Azure/azure-cosmosdb-node#224]
The right behavior is the SDK doing the aggregation and return a single value for aggregate queries.

https://stackoverflow.com/questions/47875869/why-does-select-count1-from-c-change-values-each-time-i-query-it-in-cosmosdb-d

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
