### ISSUE TITLE
Headers not returned in toArray() if there are results

### ISSUE THREAD

**Issue by gluwer** [Azure/azure-cosmosdb-node#229]
Hi,

I know that for `toArray()` it is not in official docummentation, but as third parameter of callback there is headers from last request returned. The problem is that it works only if there are no results in the query.

The cause is line https://github.com/Azure/azure-documentdb-node/blob/a16b82152f37886dec1d7d7eb301e769179f73ef/source/lib/queryIterator.js#L144 which is executed also in the last callback call which has all params set to undefined effectively clearing the value for all queries that have some results.

Regards,
Rafal

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
