### ISSUE TITLE
Need way to set agent or at least maxSockets

### ISSUE THREAD

**Issue by plasne** [Azure/azure-cosmosdb-node#234]
Since Azure Web Apps (as well as other services) use SNAT for outbound connections there can be a very limited number of outbound ports available (~128) and those are shared among all the other service calls the application might be making. The agent appears to be set for maxSockets: infinity.

The best implementation if this didn't mess anything else up would seem to be to accept an existing agent that the user provides similar to how this is implemented in the Service Bus SDK. However, at least if maxSockets were allowed to be set that would solve the problem.

**Comment by srinathnarayanan** [comment]
The latest version of the SDK has maxSockets: 256. We are working on a patch that would allow the agent to be passed in as part of the connectionPolicy that sets up the document client. Meanwhile, would you like to send a PR for this?

**Comment by christopheranderson** [comment]
In the current version of the SDK, you can modify the agent on the documentClient itself to customize this.

In the next version of the SDK, we'll expose a options object which allows you to pass a https.Agent as part of the constructor to control the configuration of how many sockets are consume.

**Comment by southpolesteve** [comment]
The v3 SDK now allows you to pass a custom agent https://github.com/Azure/azure-cosmos-js/issues/386#issuecomment-514835539
