### ISSUE TITLE
Some helpers throw strings which are hard to debug

### ISSUE THREAD

**Issue by princjef** [Azure/azure-cosmosdb-node#235]
When working with the SDK, some usage mistakes result in the client throwing strings. In a system with multiple components, this becomes very hard to debug because there's no stack trace to figure out where the error came from. Can these be switched to `throw new Error(str)` rather than `throw str`?

A cursory scan revealed the following strings being thrown (there may be more I missed):

 * https://github.com/Azure/azure-documentdb-node/blob/c9d547b63c852f3c95901bffcfb27312f1120514/source/lib/helper.js#L51
 * https://github.com/Azure/azure-documentdb-node/blob/c9d547b63c852f3c95901bffcfb27312f1120514/source/lib/helper.js#L60
 * https://github.com/Azure/azure-documentdb-node/blob/c9d547b63c852f3c95901bffcfb27312f1120514/source/lib/helper.js#L65
 * https://github.com/Azure/azure-documentdb-node/blob/c9d547b63c852f3c95901bffcfb27312f1120514/source/lib/helper.js#L70

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
