### ISSUE TITLE
QUESTION: How to specify unique keys using DocumentClient.createCollection

### ISSUE THREAD

**Issue by rfigueroa** [Azure/azure-cosmosdb-node#236]
On the Azure portal when creating a collection you are able to add unique keys.
How can you do this using the Node sdk?

**Comment by arichiardi** [comment]
I am interested too, I am reading this in the docs:

> Unique keys are supported by the latest versions of the .NET and .NET Core SQL SDKs, and the MongoDB API. The Table API and Graph API do not support unique keys at this time.

Is there a plan to support the functionality in the node client as well?

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
