### ISSUE TITLE
Usage of undefined Partition keys in Typescript

### ISSUE THREAD

**Issue by PrashanthCorp** [Azure/azure-cosmosdb-node#238]
There was a solution outlined in #222 regarding queries about documents missing the partition key. Note however, that while `partitionKey: {}` works, `partitionKey: "{}"` does not.
In light of that, it looks like partition key value should allow empty objects as valid values. 

However, neither the typings in this package nor in the @types/documentdb package seem to acknowledge this. [Here's](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/documentdb/index.d.ts#L72) the mention in the @types/documentdb. 

Would it be possible to add some clear documentation about this?

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
