### ISSUE TITLE
Add support for connection string

### ISSUE THREAD

**Issue by pgraham** [Azure/azure-cosmosdb-node#240]
I'm currently trying to connect using a connection string instead of separate endpoint and auth keys but am getting and error:

```
const client = new DocumentClient('AccountEndpoint=https://<dbname>.documents.azure.com:443/;AccountKey=<primary-key>;');
```

Attempting to perform any action with this client results in the following:

`Error: connect ECONNREFUSED 127.0.0.1:443`

Connection strings are provided in the Azure Portal UI and are easier to manage than an endpoint/authKey pairs. Please consider adding support for connecting in this manner.

Thanks!

**Comment by pgraham** [comment]
To anyone who finds this, you can provide your own support for this using the _cookie_ module:

```
const cookie = require('cookie');
const connInfo = cookie.parse('AccountEndpoint=...;AccountKey=...');
const db = new DocumentClient(connInfo.AccountEndpoint, { masterKey: connInfo.AccountKey });
```

Still, having this built in would be nice.

**Comment by christopheranderson** [comment]
What if we shipped a connection string parser? 

```typescript
const settings = DocumentClient.parseConnectionString("");
const client = new DocumentClient(setting.endpoint, {masterKey: settings.masterKey});
```

Issues I can see with supporting connection string directly in the constructor is the error handling becomes messier for parsing errors.

**Comment by southpolesteve** [comment]
This is supported in the v3 SDK: https://github.com/Azure/azure-cosmos-js
