### ISSUE TITLE
connectionPolicy.EnableEndpointDiscovery and the Emulator

### ISSUE THREAD

**Issue by samuelkilada** [Azure/azure-cosmosdb-node#248]
Hello,

When running the emulator on a server for dev purposes and connecting from another PC, it took sweat and tears to get this to work. I knew it was connecting to the remote emulator, but it was timing out for any queries. The answer? Add this to the connection policies:

connectionPolicy.EnableEndpointDiscovery = false;

Don't ask me why that fixes it, I just want other people to be aware in case they're stuck.

**Comment by christopheranderson** [comment]
This is interesting. I'll take a look.

**Comment by GustavoMoreiraPT** [comment]
Hi @christopheranderson @samuelkilada,

Just saw your post.
Did you find anything about this issue?
I have a project where I am using Cosmos emulator for developing purposes.
With EnableEndpointDiscovery set to true, after a first successful request, if I turn of the emulator, the request is taking 4/5 minutes before timing out.
I need this property set to true in live environment. 

Is this only happening in the emulator?

Thank you,

Gustavo Moreira

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
