### ISSUE TITLE
Trying to use @azure/cosmos causes exception

### ISSUE THREAD

**Issue by vinnytheviking** [Azure/azure-cosmosdb-node#250]
Good afternoon,

I'm trying to access cosmosdb from a react/typescript application. I've imported the library and trying to just read a database. I'm using the v2 @azure/cosmos npm rather than documentdb npm. I was getting CORS issues with documentdb so trying to see if v2 fixes that.

These are the exceptions showing in the client.

ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/queryIterator.d.ts:68:25 
    TS2304: Cannot find name 'AsyncIterable'.
ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/request/request.d.ts:17:55 
    TS2694: Namespace '"url"' has no exported member 'UrlWithStringQuery'.
ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/retry/retryUtility.d.ts:44:17 
    TS2694: Namespace '"url"' has no exported member 'UrlWithStringQuery'.
ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/retry/sessionReadRetryPolicy.d.ts:32:70 
    TS2694: Namespace '"url"' has no exported member 'UrlWithStringQuery'.

Any ideas how I fix these.

**Comment by southpolesteve** [comment]
@vinnytheviking Can you open this same issue over in https://github.com/Azure/azure-cosmos-js? We'll track it there.

**Comment by timmyreilly** [comment]
The issue on the other repo: https://github.com/Azure/azure-cosmos-js/issues/100
