### ISSUE TITLE
Azure ML Error

### ISSUE THREAD

**Issue by knaras** [Azure/azure-cosmosdb-node#251]
I am getting this error in Python 3 Notebook:
AzureMLUnauthorizedError: Unauthorized, please check your workspace ID and authorization token ({"Error":{"Code":"UserError","Message":"Attempted access to https://studioapi.azureml.net/api/workspaces/594546692e674ca9a7e702f1590ad07f/experiments is not authorized and has been denied.","Target":null,"Details":[],"InnerError":null,"DebugInfo":null}})

**Comment by knaras** [comment]
THE CODE IS AS FOLLOWS:
from azureml import Workspace
ws = Workspace(workspace_id = '594546692e674ca9a7e702f1590ad07f',
              authorization_token = '+GxGlr3YAObtnNXpc6GBoGQQnoF/UfaxU7lPa+GgKnzQf2//A0eBLMubNgfPRbj5KqelQMB2HiJ/URnRmwPG6g==')
experiment = ws.experiments['594546692e674ca9a7e702f1590ad07f']
ds = experiment.get_intermediate_dataset(
    node_id='ff56d765-8aa4-40f6-aa9c-dcd24dbf589e-78',
    port_name='Results dataset',
    data_type_id='GenericCSV'
)
frame = ds.to_dataframe()

**Comment by christopheranderson** [comment]
I think you have the wrong repo. This is the Cosmos DB Node SDK repo. Your code is Azure ML and Python based. Try here maybe? https://github.com/Azure/Azure-MachineLearning-ClientLibrary-Python
