### ISSUE TITLE
Query: what's the difference between this lib and azure-cosmos-js

### ISSUE THREAD

**Issue by tedyyu** [Azure/azure-cosmosdb-node#254]
this: https://github.com/Azure/azure-cosmosdb-node/
that: https://github.com/Azure/azure-cosmos-js/

thanks in advance.

**Comment by southpolesteve** [comment]
@tedyyu This repo is version 1 of the SDK, while https://github.com/Azure/azure-cosmos-js/ is version 2 and other future versions. You should be using Azure/azure-cosmos-js for new projects and also migrating old projects if possible. I'll talk with the team about adding some docs to make this clearer.

**Comment by tedyyu** [comment]
thanks for quick response, really answers my puzzle. @southpolesteve
