### ISSUE TITLE
continuation token not working when querying cosmos db by invoke rest method 

### ISSUE THREAD

**Issue by inos2006** [Azure/azure-cosmosdb-node#255]
I have thousands of data that I am querying from cosmos db with invoke rest method. I wanted to keep "x-ms-max-item-count" = 1000 and use x-ms-continuation to get to the next page when my PowerShell script run for the next time. But it is throwing 400 bad request. How do I fix it or is there any limitation of the cosmos db over the rest api call?

**Comment by EricDahlvang** [comment]
I'm not receiving an x-ms-continuation:

```js
this.client = new CosmosClient({ endpoint: settings.serviceEndpoint, key: settings.authKey });
const { database } = await this.client.databases.createIfNotExists({ id: this.settings.databaseId });
const { container } = await database.containers.createIfNotExists({ id: this.settings.collectionId });

let options = { 
	enableCrossPartitionQuery: true, 
	maxItemCount: 2, 
	continuation: continuationToken
};

let querySpec = {query: "SELECT * FROM root c ORDER BY c.timestamp DESC"};
let queryIterator = await container.items.query(querySpec, options);
let items = await queryIterator.fetchNext();

console.log(items.continuation);
```

It is very difficult to find documentation too.  I guess I'm switching back to DocumentClient.

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package `@azure/cosmos` as soon as possible. If you encounter any issues, you can raise them in the [Azure central SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
