### ISSUE TITLE
saving bool value in cosmosdb

### ISSUE THREAD

**Issue by bharatvijji** [Azure/azure-cosmosdb-node#256]
i am trying to save boolean value in cosmosdb, When i save the value as true i can see the property value as true but when i save the value as false the property is missing. Any help appritiated

**Comment by southpolesteve** [comment]
@bharatvijji Are you using the latest version of the SDK over here? https://github.com/Azure/azure-cosmos-js. This repo is for our older v1 SDK. Could you provide a simple sample script that reproduces the issue?

**Comment by bharatvijji** [comment]
i am using c# to save it

**Comment by bharatvijji** [comment]
creating issue in c# branch
