### ISSUE TITLE
Parameterized SQL queries with IN keyword 

### ISSUE THREAD

**Issue by willnix86** [Azure/azure-cosmosdb-node#258]
Creating a new issue as #247 was closed but it is still an issue as evidenced by the comments in the closed ticket, and my own experience with CosmosDB

**Comment by southpolesteve** [comment]
The last comment (https://github.com/Azure/azure-cosmosdb-node/issues/247#issuecomment-557965650) has a query that was working for me in the latest SDK. Can you provide code that reproduces the issue you are seeing?

I also highly recommend upgrading to `@azure/cosmos` SDK. `documentdb` has been deprecated.

**Comment by southpolesteve** [comment]
Closing this issue as stale. If you are still encountering issues, please file an issue in the new central Azure SDK repo: https://github.com/Azure/azure-sdk-for-js
