### ISSUE TITLE
Could not parse the provided connection string

### ISSUE THREAD

**Issue by khandg** [Azure/azure-cosmosdb-node#260]
Trying to initiate using below:

`const client = new CosmosClient('mongodb://picpaxnutrition:xxxxzzzzzaaaaaaaaaazzz==@picpaxnutrition.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@picpaxnutrition@');`
 
but getting the subject mentioned error. This is the primary connection string copied from the Azure portal. Have tried the same with the secondary but the same result.

Thanks

**Comment by southpolesteve** [comment]
Its appears you are trying to use the @azure/cosmos SDK with a Mongo account. This is not supported. Use the official Mongo drivers instead. @azure/cosmos is only used with SQL accounts.

As a side note, this repo is no longer maintained. Development has moved to our unified Azure JS SDK repo https://github.com/Azure/azure-sdk-for-js
