### ISSUE TITLE
Azure Cosmos DB Library invoking twice

### ISSUE THREAD

**Issue by harikapampatti** [Azure/azure-cosmosdb-node#262]
Hi,

Iam using RBAC to establish the connection to cosmosdb but its making a call to login.microsoftonline.com twice.
why 2 calls are being invoked?

Attached below sceenshot for refence.
![image](https://user-images.githubusercontent.com/48385777/129885280-f413c21e-f01e-414d-85e0-057b5891a74b.png)

below is my code

```
servicePrincipal = new ClientSecretCredential(
    tenantId,
    clientId,
    clientSecret);
rbacClient = new CosmosClient({
    endpoint,
    aadCredentials: servicePrincipal
});

  const database = rbacClient.database(DB_NAME);
        const container = database.container(containerId);
        var response = await container.items.bulk(operations, { continueOnError: true });
```

Can anyone please help  ..what is the rationale behind the call?

Thanks in advance!!

**Comment by zfoster** [comment]
Hi @harikapampatti this repo is deprecated - https://github.com/Azure/azure-cosmosdb-node#deprecated-

Please refer to https://github.com/Azure/azure-sdk-for-js for creating new issues related to the cosmos node SDK
