### ISSUE TITLE
api documentation does not include description of Indexing policy members

### ISSUE THREAD

**Issue by siritsch** [Azure/azure-cosmosdb-node#51]
The createCollection method takes an Object of type IndexingPolicy as the second parameter. In the documentation there is link listing the members of IndexingPolicy but the members are not explained in detail. For example the docu says that IncludedPaths is an array of IndexPath. This structure has a Path member saying only that this is a string containg the path to be indexed. But there are several constraints to those string. 
A good explanation of those constraints can be found here: https://github.com/Azure/azure-content/blob/master/articles/documentdb-indexing-policies.md . So this link should be also included into the api documentation.

**Comment by southpolesteve** [comment]
We have recently announced deprecation version 1.x of the Azure Cosmos JavaScript SDK. We will end support for the `documentdb` package and this repo on August 30, 2020. Please update to our new package [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) as soon as possible. If you encounter any issues, you can raise them in the [Azure central JS SDK repo](https://github.com/Azure/azure-sdk-for-js). If something is preventing you from upgrading to the latest version of the SDK, you can always email me directly: stfaul@microsoft.com
